EmployeeEvaluator/Models/Evaluation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using EmployeeEvaluator.Models.Validation;

namespace EmployeeEvaluator.Models
{
    public class Evaluation
    {
        [Key]
        public int EvaluationID { get; set; }
        public int CohortID { get; set; }
        public int? EmployeeID { get; set; }
        public int? RaterID { get; set; }
        public int? EvalTypeID { get; set; }
        public int? EvalStageID { get; set; }
        public bool Completed { get; set; }
        [DisplayName("Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        [DateBefore]
        public DateTime StartDate { get; set; }
        [DisplayName("End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        [Required]
        public DateTime EndDate { get; set; }
        public bool Pending { get; set; }
        public virtual EvalType EvalType { get; set; }
        public virtual EvalStage EvalStage { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Rater Rater { get; set; }

        public virtual ICollection<Question> Questions { get; set; }

        public Evaluation()
        {
            Questions = new List<Question>();
        }
    }
}

EmployeeEvaluator/Models/EvaluationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeEvaluator.Models
{
    public class EvaluationViewModel
    {
        public Evaluation Evaluation { get; set; }
        public IEnumerable<SelectListItem> EvalTypes { get; set; }
        public IEnumerable<SelectListItem> EvalStages { get; set; }
        public EvalType EvalType { get; set; }
        public EvalStage EvalStage { get; set; }
    }
}

EmployeeEvaluator/Controllers/EvaluationController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Diagnostics.Eventing.Reader;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Web.Mvc;
using EmployeeEvaluator.DAL;
using EmployeeEvaluator.Migrations;
using EmployeeEvaluator.Models;
using SendGrid;

namespace EmployeeEvaluator.Controllers
{
    public class EvaluationController : Controller
    {
        private UnitOfWork unitOfWork;
        private EvaluatorContext db;
        private int RaterId;
        private Boolean isTest = false;

        public EvaluationController()
        {
            unitOfWork = new UnitOfWork();
            this.db = new EvaluatorContext();
            this.RaterId = -1;
        }

        public EvaluationController(IRepository<Evaluation> repository)
        {
            unitOfWork = new UnitOfWork();
            unitOfWork.EvaluationRepository = repository;
            this.RaterId = -1;
        }

        public EvaluationController(IRepository<Evaluation> evaluationRepository, IRepository<Cohort> cohortRepository, IRepository<Employee> employeeRepository, IRepository<EvalStage> stageRepository, IRepository<MaxRater> maxRaterRepository, IRepository<RaterRole> raterRoleRepository, IRepository<Category> categoryRepository, IRepository<EvalType> typeRepository, IRepository<Rater> raterRepository)
        {
            unitOfWork = new UnitOfWork();
            unitOfWork.EvaluationRepository = evaluationRepository;
            unitOfWork.CohortRepository = cohortRepository;
            unitOfWork.EmployeeRepository = employeeRepository;
            unitOfWork.StageRepository = stageRepository;
            unitOfWork.MaxRaterRepository = maxRaterRepository;
            unitOfWork.RaterRoleRepository = raterRoleRepository;
            unitOfWork.CategoryRepository = categoryRepository;
            unitOfWork.TypeRepository = typeRepository;
            unitOfWork.RaterRepository = raterRepository;
            this.RaterId = -1;
            this.isTest = true;
        }

        // GET: Evaluation
        public ActionResult Index()
        {
            if (authenticatedAsEmployee())
            {
                using (unitOfWork)
                {
                    var evaluationViewModels = new List<EvaluationViewModel>();
                    var currentEmployee = unitOfWork.EmployeeRepository.GetByID((int)Session["LoggedInEmployeeID"]);
                    var evaluations = new List<Evaluation>();

                    var numberOfSupervisors = 0;
                    var numberOfCoworkers = 0;
                    var numberOfSupervisees = 0;

                    if (currentEmployee.Raters == null)
                    {
                        TempData["Error"] = "You do not have enough raters to complete an evaluation.";
                        return View(evaluationViewModels);
                    }
                    else
                    {
                        evaluations = currentEmployee.Evaluations.Where(e => e.Completed == false && e.RaterID == null).ToList();
                    }

                    foreach (var rater in currentEmployee.Raters)
                    {
                        if (rater.Active)
                        {
                            var raterRole = unitOfWork.RaterRoleRepository.GetByID(rater.RaterRoleID);
                            if (raterRole.RoleName != null)
                            {
                                if (raterRole.RoleName.Equals("Supervisor"))
                                {
                                    numberOfSupervisors++;
                                }
                                else if (raterRole.RoleName.Equals("Coworker"))
                                {
                                    numberOfCoworkers++;
                                }
                                else if (raterRole.RoleName.Equals("Supervisee"))
                                {
                                    numberOfSupervisees++;
                                }
                            }
                        }

                    }
                    var maxRaters = unitOfWork.MaxRaterRepository.Get().ToList();

                    if (numberOfSupervisors < maxRaters[0].Max)
                    {
                        TempData["Error"] = "You do not have enough " + maxRaters[0].RaterRole.RoleName + "s to complete an evaluation.";
                        return View(evaluationViewModels);
                    }
                    if (numberOfSupervisees < maxRaters[1].Max)
                    {
                        TempData["Error"] = "You do not have enough " + maxRaters[1].RaterRole.RoleName + "s to complete an evaluation.";
                        return View(evaluationViewModels);
                    }
                    if (numberOfCoworkers < maxRaters[2].Max)
                    {
                        TempData["Error"] = "You do not have enough " + maxRaters[2].RaterRole.RoleName + "s to complete an evaluation.";
                        return View(evaluationViewModels);
                    }

                    var cohort = unitOfWork.CohortRepository.GetByID(currentEmployee.CohortID);
                    if (!cohort.Stable)
                    {
                        TempData["Error"] = "Your cohort is not stable.  Please contact your administrator.";
                        return View(evaluationViewModels);
                    }
                    if (evaluations != null)
                    {
                        foreach (var evaluation in evaluations)
                        {
                            var evaluationViewModel = new EvaluationViewModel();
                            evaluationViewModel.Evaluation = evaluation;
                            evaluationViewModel.EvalType = unitOfWork.TypeRepository.GetByID(evaluation.EvalTypeID);
                            evaluationViewModel.EvalStage = unitOfWork.StageRepository.GetByID(evaluation.EvalStageID);
                            evaluationViewModels.Add(evaluationViewModel);
                        }
                        return View(evaluationViewModels);
                    }
                }


                return View();
            }
            return RedirectToAction("EmployeeLogin", "Home");

        }

        // GET: Evaluation/Details/5
        public ActionResult Details(int? id)
        {
            using (unitOfWork)
            {
                if (id == null)
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                var evaluationViewModel = new EvaluationViewModel();
                var evaluation = unitOfWork.EvaluationRepository.GetByID(id);

                if (evaluation == null)
                {
                    TempData["Error"] = "Your cohort is not stable.  Please contact your administrator.";
                    return View();
                }
                evaluationViewModel.Evaluation = evaluation;
                evaluationViewModel.EvalType = unitOfWork.TypeRepository.GetByID(evaluation.EvalTypeID);
                return View(evaluationViewModel);
            }
            
        }

        // GET: Evaluation/Create
        [HttpGet]
        public ActionResult Create(int id)
        {
            if (this.authenticatedAsAdmin())
            {
                using (unitOfWork)
                {
                    if (TempData.ContainsKey("ModelState"))
                        ModelState.Merge((ModelStateDictionary)TempData["ModelState"]);
                    var evaluationViewModel = new EvaluationViewModel();
                    evaluationViewModel.Evaluation = new Evaluation();
                    evaluationViewModel.Evaluation.CohortID = id;
                    evaluationViewModel.EvalTypes =
                        unitOfWork.TypeRepository.Get().ToList().Select(x => new SelectListItem
                        {
                            Value = x.EvalTypeID.ToString(),
                            Text = x.TypeName
                        });
                    evaluationViewModel.EvalStages =
                        unitOfWork.StageRepository.Get().ToList().Select(x => new SelectListItem
                        {
                            Value = x.EvalStageID.ToString(),
                            Text = x.StageName
                        });
                    evaluationViewModel.Evaluation.StartDate = DateTime.Now;
                    evaluationViewModel.Evaluation.EndDate = DateTime.Now;


                    return View(evaluationViewModel);
                }
            }
            return RedirectToAction("AdminLogin", "Home");
        }

        // POST: Evaluation/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "EvalTypeID,EvalStageID,Type,Stage,CohortID,Completed,StartDate,EndDate")] Evaluation evaluation)
        {
            if (authenticatedAsAdmin())
            {
                using (unitOfWork)
                {
                    var cohort = unitOfWork.CohortRepository.GetByID(evaluation.CohortID);
                    var evaluations = unitOfWork.EvaluationRepository.Get()
                        .Where(e => e.CohortID == evaluation.CohortID && e.Completed && e.Pending && e.EvalTypeID == evaluation.EvalTypeID).ToList();
                    var employees =
                        unitOfWork.EmployeeRepository.Get().Where(e => e.CohortID == evaluation.CohortID).ToList();

EmployeeEvaluator/Views/Evaluation/Completed.cshtml
@model IEnumerable<EmployeeEvaluator.Models.EvaluationViewModel>

@{
    ViewBag.Title = "Completed";
}

<h2>Completed</h2>
<p style="color: red; padding-left : 162px">@TempData["Error"]</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Evaluation.CohortID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EvalType.TypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Evaluation.Stage)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Evaluation.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Evaluation.EndDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Evaluation.CohortID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EvalType.TypeName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Evaluation.Stage)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Evaluation.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Evaluation.EndDate)
        </td>
        <td>
            @Html.ActionLink("View Answers", "OpenCompleted", new { id=item.Evaluation.EvaluationID })
        </td>
    </tr>
}

</table>

EmployeeEvaluator/Views/Evaluation/Create.cshtml
@model EmployeeEvaluator.Models.EvaluationViewModel


<h2>Create Evaluation</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.HiddenFor(model => model.Evaluation.CohortID)

        <p style="color: red; padding-left : 162px">@TempData["Confirmation"]</p><br/>

        <hr/>
        @Html.ValidationSummary(true, "", new {@class = "text-danger"})
        
        <div class="form-group">
            @Html.LabelFor(model => model.EvalType.TypeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Evaluation.EvalTypeID, Model.EvalTypes, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.EvalStage.StageName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Evaluation.EvalStageID, Model.EvalStages, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Evaluation.StartDate, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Evaluation.StartDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Evaluation.StartDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Evaluation.EndDate, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Evaluation.EndDate, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.Evaluation.EndDate, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Cohort", null, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeEvaluator/Views/Evaluation/Delete.cshtml
@model EmployeeEvaluator.Models.EvaluationViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Evaluation</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EvalType.TypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EvalType.TypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Evaluation.EvalStage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Evaluation.EvalStage)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Evaluation List", "Index")
        </div>
    }
</div>

EmployeeEvaluator/Views/Evaluation/Details.cshtml
@model EmployeeEvaluator.Models.EvaluationViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Evaluation Details</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.EvalType.TypeName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EvalType.TypeName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Evaluation.Stage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Evaluation.Stage)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to Evaluation List", "Index")
</p>

EmployeeEvaluator/Views/Evaluation/Edit.cshtml
@model EmployeeEvaluator.Models.EvaluationViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Evaluation</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Evaluation.EvaluationID)

        <div class="form-group">
            @Html.LabelFor(model => model.EvalType.TypeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Evaluation.EvalTypeID, Model.EvalTypes, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Evaluation.EvalStage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Evaluation.EvalStage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Evaluation.EvalStage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Evaluation List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeEvaluator/Views/Evaluation/Index.cshtml
@using System.Security.Cryptography
@using System.Text
@using System.Text.RegularExpressions
@model IEnumerable<EmployeeEvaluator.Models.EvaluationViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Evaluations</h2>
<p style="color: red; padding-left : 162px">@TempData["Error"]</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EvalType.TypeName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EvalStage.StageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Evaluation.StartDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Evaluation.EndDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EvalType.TypeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EvalStage.StageName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Evaluation.StartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Evaluation.EndDate)
            </td>
            <td>
                @if (DateTime.Compare(item.Evaluation.StartDate, DateTime.Now) < 0 && DateTime.Compare(item.Evaluation.EndDate, DateTime.Now) > 0)
                {
                    string salt = "92429dsdaa41e930d86c6de4ebda9602d55c39986";
                    var bytes = Encoding.UTF8.GetBytes(item.Evaluation.EvaluationID + salt);
                    var hashedID = Convert.ToBase64String((new SHA256Managed()).ComputeHash(bytes));

                    Regex rgx = new Regex("[^a-zA-Z0-9 -]");
                    hashedID = rgx.Replace(hashedID, "");
                    @Html.ActionLink("Start Evaluation", "Start", new { id = hashedID })
                }  
            </td>
        </tr>
    }

</table>
<div>
    @Html.ActionLink("Back to Employee Dashboard", "Index", "Employee")
</div>

EmployeeEvaluator/Views/Evaluation/OpenCompleted.cshtml
@model IEnumerable<EmployeeEvaluator.Models.Question>

@{
    ViewBag.Title = "OpenCompleted";
}

<h2>Evaluation Answers</h2>

<table class="table">

@foreach (var item in Model)
{
    foreach (var answer in item.Answers)
    {
        if (answer.Selected)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.QuestionText) : @Html.DisplayFor(modelItem => answer.AnswerText)
                </td>
            </tr>
        }

    }

}

</table>

EmployeeEvaluator/Views/Evaluation/Start.cshtml
@using EmployeeEvaluator.Models
@model EmployeeEvaluator.Models.StartEvaluationViewModel

@{
    ViewBag.Title = "Start Evaluation";
}


@using (Html.BeginForm("Start", "Evaluation", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Evaluation.EvaluationID)
    @Html.HiddenFor(model => model.Evaluation.CohortID)
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Evaluation</h4>
        <hr />
        <p style="color: red; padding-left : 162px">@TempData["Error"]</p>
        @if (Model.Categories != null)
        {
            foreach (var category in Model.Categories)
            {
                if (category.EvalType.TypeName.Equals("Type 1"))
                {
                    <div class="form-group">
                        @Html.DisplayFor(model => category.CategoryName):<br>
                        @Html.DisplayFor(model => category.CategoryDescription)
                        <br><br>
                        @foreach (var question in category.Questions)
                        {
                            @Html.DisplayFor(model => question.QuestionText)
                            <br>
                            <br>
                            for (int i = 1; i <= 5; i++)
                            {
                                if (question.SelectedAnswerValue != null && i == question.SelectedAnswerValue.Value)
                                {
                                    <span class="question">@Html.DisplayFor(model => i)</span>
                                    @Html.RadioButton(category.CategoryName + question.QuestionText, i, true)
                                }
                                else
                                {
                                    <span class="question">@Html.DisplayFor(model => i)</span>
                                    @Html.RadioButton(category.CategoryName + question.QuestionText, i)
                                }
                            }
                            <br>
                            <br>
                            <br>
                        }
                    </div>
                }
                else
                {
                    <div class="form-group">
                        @Html.DisplayFor(model => category.CategoryName):<br>
                        @Html.DisplayFor(model => category.CategoryDescription)
                        <br><br>
                        @foreach (var question in category.Questions)
                        {
                            @Html.DisplayFor(model => question.QuestionText)
                            <br>
                            <br>
                            for (int i = 1; i <= 10; i++)
                            {
                                if (question.SelectedAnswerValue != null && i == question.SelectedAnswerValue.Value)
                                {
                                    <span class="question">@Html.DisplayFor(model => i, true)</span>
                                    @Html.RadioButton(category.CategoryName + question.QuestionText, question.SelectedAnswerValue, true)
                                }
                                else
                                {
                                    <span class="question">@Html.DisplayFor(model => i)</span>
                                    @Html.RadioButton(category.CategoryName + question.QuestionText, i)
                                }
                            }
                            <br>
                            <br>
                            <br>
                        }
                    </div>
                }
            }
        }
        @if (Model.Categories != null)
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Submit Evaluation" class="btn btn-default" />
                </div>
            </div>
        }
        

    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EmployeeEvaluator/Views/Evaluation/Submit.cshtml
@{
    ViewBag.Title = "Submit";
}

<h2>Thank you for submitting your evaluation.</h2>